### ISSUE TITLE
Dependency Error with Aura Skin and Kodi 17.6

### ISSUE THREAD

**Issue by icpryde** [13Clowns/_zips#10]
I'm now receiving a dependency error because I'm on Kodi 17.6 and I have the Aura skin for 17.6, you created an aura skin update 1.0.0 and its causing issues with the 17.6 skin as it won't install that specific dependency. Please make it so this update is either not required for 17.6 users or have it so the update plays nice with 17.6 as well.

Heres my log file.

Kodi log: https://paste.ubuntu.com/p/FJPfJfCmM2/

Kodi.old.log: https://paste.ubuntu.com/p/dw9XyzCjJ2/

Wizard log: https://paste.ubuntu.com/p/6txz6jMNt9/

**Comment by icpryde** [comment]
Heres a picture as well of what I'm seeing http://oi65.tinypic.com/1498lud.jpg

**Comment by 13Clowns** [comment]
removed aura
