### ISSUE TITLE
plugin.video.13clowns & civitasscrapers

### ISSUE THREAD

**Issue by mgonzales71** [13Clowns/_zips#9]
First let me say - nice start for a new community based scraper set - they actually work well and provide a good many results *(I am using real-debrid so that helps but even better results than typical with other addon / scrapers).  So thanks and keep up the great work.

I know everything is in dev / beta so I don't expect anything besides something could be broken and prob wont work etc 

so I just wanted to mention that artwork at the tv show level *(mytvshows via trakt) don't appear to have any artwork (banners) - I am using my own api's for tvdb and fanart.tv so maybe I should try without just in case (so apologies if that becomes the case).

But one of the BIG requests of you with your new video addon is that when playing back a tv show via library integration that you populate the clearlogo, clearart, landscape, etc (all tv show arts) for skins to utilize as they would for playing back a video file itself... I am hoping that if you can't set the appropriate $INFO labels that you maybe provide alternative $INFO labels for the artwork - the last addon that did this well was SALTS.

Thanks for the consideration and your contributions!

**Comment by mgonzales71** [comment]
OH and if you have not heard of or used this addon - please consider making a provider installer based on your scrapers also!  

maybe he'd be open to some collaboration even?  his addon is very neat and unique

https://github.com/nixgates/plugin.video.seren

**Comment by SerpentDrago** [comment]
> OH and if you have not heard of or used this addon - please consider making a provider installer based on your scrapers also!
> 
> maybe he'd be open to some collaboration even? his addon is very neat and unique
> 
> https://github.com/nixgates/plugin.video.seren

Once the scraper set stabilizes a bit and we are sure there will be no structure changes , a Provider zip for seren will be provided by either 13 clowns or A4k

**Comment by jewbmx** [comment]
Got a suggestion for ya Clowns, modify the addon.xml to be like this...

<import addon="blah.blah.blah" optional= "true" />

Your main scraper mod should be normal as it already is but the spare ones like global and eggs are forced even tho they are pretty much spares.

**Comment by 13Clowns** [comment]
man i need to look at this more. Thanks @jewbmx . Changes made to just use civitas now.
